#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H
#define NRF_SDH_ENABLED 1
#define NRF_SDH_BLE_ENABLED 1
#define NRF_SDH_BLE_VS_UUID_COUNT 1
#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 1
#define NRF_SDH_BLE_GAP_DATA_LENGTH 251
#define NRF_SDH_BLE_GATT_MAX_MTU_SIZE 247
#define NRF_BLE_GATT_ENABLED 1
#define NRF_SDH_BLE_OBSERVER_PRIO 3

#define NRFX_CLOCK_ENABLED 1
#define NRFX_CLOCK_CONFIG_LF_SRC 1

#define APP_TIMER_ENABLED 1
#define NRF_PWR_MGMT_ENABLED 1
#define NRFX_SAADC_ENABLED 1
#define NRFX_SAADC_CONFIG_LP_MODE 1
#define NRF_DRV_TWI_ENABLED 1
#define TWI0_ENABLED 1
#define NRFX_GPIOTE_ENABLED 1
#define PEER_MANAGER_ENABLED 1
#endif
